# Generated by Django 2.2.4 on 2019-08-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text'), ('radio', 'Radio'), ('select', 'Select'), ('select-multiple', 'Select Multiple'), ('integer', 'Integer')], default='text', max_length=200),
        ),
    ]
